### PR TITLE
Use spack to build cp2k inside a container

### PR DESCRIPTION
**Pull request by mtaillefumier**
This docker container uses the already provided docker image with rocm

- **WARNING**: a bug in gcc 13 and 14 is triggered  when any of these version is used to build cp2k
- [x] Need to update the README file
- [ ]  Some cleanup needed
- [ ] pass gcc version as a parameter to generate the container
- [ ] for completeness `openmpi` should probably be built with spack 
- [x] Lock spack and cp2k versions (use develop and master for both)

### CODE REVIEW

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    - spglib
+    - dftd4
+    - hdf5
+    - hip
+    - hipblas
+    - hipfft
+    - hipcc
+    - trexio
+    - gcc@12
+    - dbcsr@develop+mpi+rocm+openmp amdgpu_target=gfx90a
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: I would like to use the "g2g" build of dbcsr. Can we add `+g2g` here?

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    - openblas
+    - libvdwxc@0.5.0
+  #- greenx
+    - cp2k@master+cosma~cuda+dbm_gpu+dftd4+grid_gpu+grpp+hdf5~ipo+libint+libxc+mpi+mpi_f08+openmp+pw_gpu+rocm+sirius+spglib+spla+tblite+trexio+vdwxc build_type=Release smm=libxsmm %gcc@12
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: I do not see dbcsr in this line, should it be added?

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+  concretizer:
+    unify: true
+  packages:
+    all:
+      variants: +shared amdgpu_target=gfx90a amdgpu_target_sram_ecc=gfx90a
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: Will this build work for `gfx942` and perhaps `gfx950` also?

File: cp2k/docker/spack.sh [hunk 4]
```diff
@@ -0,0 +1,10 @@
+#!/bin/bash
+
+source /opt/spack/share/spack/setup-env.sh
+
+spack env activate /opt/cp2k_environment
+spack external find --all
+spack concretize -f
+spack install -j16
+ln -s `spack find -p cp2k@master | tail -n 1 | awk -e 'BEGIN{FS=" "} {print $2}'` /opt/cp2k
```
Comment (gsitaram) [inline cp2k/docker/spack.sh]: Building the docker container failed at this line, and removing the `-e` option from the awk command seems to fix the problem. Can this be done?
-ln -s `spack find -p cp2k@master | tail -n 1 | awk -e 'BEGIN{FS=" "} {print $2}'` /opt/cp2k
+ln -s `spack find -p cp2k@master | tail -n 1 | awk 'BEGIN{FS=" "} {print $2}'` /opt/cp2k

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+      target: [zen3]
+
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml:45]: I was wondering if it was possible to build 2 different cp2k binaries in the container. 
1. with dbcsr GPU + G2G, no PW GPU --> for running DFT benchmark.
2. without DBCSR GPU, keep PW GPU --> for running the RPA benchmark. But I think it is not possible to turn off GPU DBCSR if ROCm/CUDA is enabled. So, in that case, the original build of CP2K with everything is fine.

Is it a good idea to build two binaries in the container? If so, does this mean we would need two different spack environments? And consequently, two different install directories (`/opt/cp2k_install` and `/opt/cp2k_install_nopwgpu`). Please see my comment in spack.sh to understand why I changed the symlink name from `/opt/cp2k` to `/opt/cp2k_install`.

File: cp2k/docker/Dockerfile [hunk 6]
```diff
@@ -79,6 +185,5 @@ ENV PATH=$PATH:/opt/cp2k/bin:/scripts \
     UCX_TLS=self,sm,tcp,rocm
 
 WORKDIR /opt/cp2k/benchmarks
```
Comment (gsitaram) [inline cp2k/docker/Dockerfile]: For context, this is what we used to do before. We had a CP2K repo clone outside of the container, and would map it to /opt/cp2k inside the container so that we could find the input files for the various benchmarks under /opt/cp2k/benchmarks.

I see that this path is now used to be a soft link to the cp2k installation dir in the container. (see last line in spack.sh). Could we change that symlink from `cp2k` to `cp2k_install`?

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 5 above)
Comment (gsitaram) [reply cp2k/docker/cp2k_environment/spack.yaml:45]: If it is too complicated, we can describe in the README how to build a container to run the DFT benchmark in words and leave it at that.

**Review by gsitaram — CHANGES_REQUESTED** [review]
Hi @mtaillefumier , thank you for your contributions. Please help clarify some of my questions.

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 1 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml]: yes. the option is +g2g

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 2 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml]: it inherit it from the list above. spack will use the spec mentioned in the package list.

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 3 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml]: yes it should at least for gfx942. I would suggest using gfx942 for gfx950 as well as dbcsr does not support them yet.

File: cp2k/docker/spack.sh (hunk 4 above)
Comment (mtaillefumier) [reply cp2k/docker/spack.sh]: it is strange. if it works the changing it to the specific container is not an issue

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 5 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml:45]: yes it is possible. the easiest is to create two distinct cp2k environments as I do not know how well spack handle multiple versions of the binary in environments. I will test this

File: cp2k/docker/Dockerfile (hunk 6 above)
Comment (mtaillefumier) [reply cp2k/docker/Dockerfile]: hmm... i will have to check

**Review by gsitaram — APPROVED** [review]
Since I want to build upon this work further, I would like to accept this PR now.

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 5 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml:45]: I created two separate environments for this.

File: cp2k/docker/Dockerfile (hunk 6 above)
Comment (mtaillefumier) [reply cp2k/docker/Dockerfile]: that makes the build more complex to effectively use a cloned repository with a spack env.

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 5 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml:45]: please ignore my last comment. We can desactivate GPU support at runtime. It is simpler

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 1 above)
Comment (mtaillefumier) [reply cp2k/docker/cp2k_environment/spack.yaml]: done

**Comment by mtaillefumier** [comment]
I modified the container build.

- we can use the turn off feature of GPU support DBCSR at runtime without rebuilding the entire environment.
- Released the `/opt/cp2k` directory so that it can be mounted at runtime
- Adjusted the symlink path to /opt/cp2k-install
- Added +g2g to the specs

**Comment by gsitaram** [comment]
@mtaillefumier , thank you! I will test on my end. Does it work only with ROCm 6.4? I wonder if we could change the base container to ROCm 7.2. I think we may still have to tackle the problem of dbcsr failing with this error though:
```
src/acc/cuda_hip/../hip/acc_hip.h:94:21: error: expected unqualified-id before numeric constant
   94 | extern unsigned int hipHostAllocDefault;
      |                     ^~~~~~~~~~~~~~~~~~~
```
This was fixed in https://github.com/cp2k/dbcsr/pull/879, but it didn't get merged even into dbcsr 2.8.0. We may have to try with dbcsr 2.9.1.

**Comment by mtaillefumier** [comment]
yes. the new changes should use dbcsr 2.9.1 by default unless I forgot to modify cp2k recipe.

**Comment by mtaillefumier** [comment]
it works with `ROCM 6.3`. however I always use dbcsr@develop personally or fix it by hand. 

I will have to create a patch for dbcsr 2.8.0 that solve this issue and open a PR in `spack-package` repo.

File: cp2k/docker/cp2k_environment/repos/packages/cp2k/package.py [hunk 7]
```diff
@@ -0,0 +1,1242 @@
...
+        default=False,
+        description="Use SPLA off-loading functionality. Only relevant when CUDA or ROCM"
+        " are enabled",
+    )
+    variant("pytorch", default=False, description="Enable libtorch support")
+    variant(
+        "openpmd-api",
+        default=False,
+        description="Enable openPMD support",
+        when="@2026.2: build_system=cmake",
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/repos/packages/cp2k/package.py]: This must be 2026.1 if I am not mistaken.

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+    - spglib
+    - dftd4
+    - hdf5
+    - hip
+    - hipblas
+    - hipfft
+    - hipcc
+    - trexio
+    - gcc@12
+    - dbcsr+mpi+rocm+openmp+g2g~tests
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: Let's also remove building examples here by adding `~examples` to this line.

**Review by gsitaram — COMMENTED** [review]
Testing now and provided 2 more comments for changes.

File: cp2k/docker/spack.sh [hunk 9]
```diff
@@ -0,0 +1,11 @@
+#!/bin/bash
+
+source /opt/spack/share/spack/setup-env.sh
+
+spack env activate /opt/cp2k_environment
+spack external find --all
+spack concretize -f
+spack install -j16
+
+ln -s `spack find -p cp2k@master | tail -n 1 | awk 'BEGIN{FS=" "} {print $2}'` /opt/cp2k
```
Comment (gsitaram) [inline cp2k/docker/spack.sh]: change the cp2k version here from `master` to `2026.1`

File: cp2k/docker/cp2k_environment/spack.yaml (hunk 8 above)
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: In addition, I had to add `dbcsr@2.9.1` and remove the `+g2g` since this is not a compile option in 2.9.1 but has been changed to a runtime option now.

File: cp2k/docker/cp2k_environment/repos/packages/libvdwxc/package.py [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+    variant("pfft", default=False, description="Enable support for PFFT")
+
+    depends_on("c", type="build")  # generated
+    depends_on("fortran", type="build")  # generated
+
+    depends_on("fftw-api@3")
+    depends_on("mpi@2:", when="+mpi")
+    depends_on("pfft", when="+pfft")
+
+    depends_on("autoconf", type="build", when="@master")
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/repos/packages/libvdwxc/package.py]: can we pin this to `autoconf@2.7.1` instead of just `autoconf`? It seems that was needed for either the docker or baremetal build that I am trying on my end.

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+  - repos
+  include: [./config.yaml]
+  # add package specs to the `specs` list
+# This is a Spack Environment file.
+#
+  specs:
+    - sirius@develop+rocm+fortran+vdwxc+dftd4+dftd3+pugixml+openmp+scalapack
+    - libxc@7+fortran build_system=cmake
+    - libint
+    - cosma+rocm+gpu_direct+rccl
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: `gpu_direct` and `rccl` led to compilation issues. Could we remove these?

File: cp2k/docker/cp2k_environment/spack.yaml [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+    - hip
+    - hipblas
+    - hipfft
+    - hipcc
+    - trexio
+    - gcc@12
+    - dbcsr+mpi+rocm+openmp+g2g~tests
+    - openblas
+    - libvdwxc@master
+    - cp2k@2026.1+cosma~cuda+dbm_gpu+dftd4+grid_gpu+grpp+hdf5~ipo+libint+libxc+mpi+mpi_f08+openmp+pw_gpu+rocm+sirius+spglib+spla+tblite+trexio+vdwxc build_type=Release smm=libxsmm %gcc@12
```
Comment (gsitaram) [inline cp2k/docker/cp2k_environment/spack.yaml]: can we remove %gcc@12 from this line? That way, I can use gcc12 that exists in the container as an external package and use the same spack.yaml for a baremetal build use with a different external package as available on a given system. Thanks!

**Review by cmcknigh — APPROVED** [review]
Based on feedback from @gsitaram this looks good to go.
